CREATE TABLE IF NOT EXISTS full_database_normalised (
    doi TEXT PRIMARY KEY,
    subtypeDescription TEXT,
    subjareas TEXT,
    main_author TEXT,
    secondary_authors TEXT,
    title TEXT,
    publicationName TEXT,
    volume TEXT,
    pageRange TEXT,
    openaccess INTEGER,
    affiliation_country TEXT,
    affiliation_city TEXT,
    affilname TEXT,
    OpenAlex_topconcepts TEXT,
    abstract TEXT,
    n_topic INTEGER,
    topic_descrip TEXT,
    keywords TEXT
);