version: '3'

services:
  postgres:
    image: postgres:15
    container_name: proj-postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: guest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  
    restart: unless-stopped

volumes:
  postgres_data: